// [autogenerated] Kilshin network - Baseline
function generatePuzzleKilshinBaseline() {
    // first record the location of each node, as an x% y% of the canvas
    var node_0_loc = [0.09760834602026522, 0.2467845861042649];
    var node_1_loc = [0.14511550672952897, 0.3897320977802634];
    var node_2_loc = [0.058919164869187184, 0.5322420980246029];
    var node_3_loc = [0.13914922238802221, 0.7636804516366898];
    var node_4_loc = [0.21655878642825163, 0.10359984692524107];
    var node_5_loc = [0.27458592724673236, 0.19898628658676243];
    var node_6_loc = [0.22652412089121848, 0.4120853070928266];
    var node_7_loc = [0.21749654493895468, 0.562178929765678];
    var node_8_loc = [0.2455646940586921, 0.7399341852338205];
    var node_9_loc = [0.25738593152160805, 0.9216807123157172];
    var node_10_loc = [0.4152704027164105, 0.08511442716927078];
    var node_11_loc = [0.34122088994204447, 0.24974624455184344];
    var node_12_loc = [0.3915786276188391, 0.4231641681760175];
    var node_13_loc = [0.38260551027398587, 0.5684478463044337];
    var node_14_loc = [0.4012093914829035, 0.7209192506715758];
    var node_15_loc = [0.40304713755553073, 0.8825673752101596];
    var node_16_loc = [0.5606844682868986, 0.12042550507673663];
    var node_17_loc = [0.5964736684191215, 0.19841075510629202];
    var node_18_loc = [0.6467441616638935, 0.4430270123671901];
    var node_19_loc = [0.5165083339897311, 0.6081188013303951];
    var node_20_loc = [0.558407057721125, 0.7252806810772887];
    var node_21_loc = [0.5650349167155481, 0.8353956094790811];
    var node_22_loc = [0.7365345241244307, 0.12160461671575133];
    var node_23_loc = [0.7511137081667025, 0.24689166696728457];
    var node_24_loc = [0.8016519893012957, 0.3676557789147757];
    var node_25_loc = [0.739812240244089, 0.5555296134602589];
    var node_26_loc = [0.7424932232827374, 0.7257180820098511];
    var node_27_loc = [0.887485640702675, 0.26944601634723664];
    var node_28_loc = [0.9137180318363167, 0.41342874830552795];
    var node_29_loc = [0.9218312069866897, 0.5869895619645998];
    var node_30_loc = [0.9339010846001771, 0.7442367153648258];

    // second create the node objects
    var node_0 = new Node(gameboard.context, node_0_loc);
    var node_1 = new Node(gameboard.context, node_1_loc);
    var node_2 = new Node(gameboard.context, node_2_loc);
    var node_3 = new Node(gameboard.context, node_3_loc);
    var node_4 = new Node(gameboard.context, node_4_loc);
    var node_5 = new Node(gameboard.context, node_5_loc);
    var node_6 = new Node(gameboard.context, node_6_loc);
    var node_7 = new Node(gameboard.context, node_7_loc);
    var node_8 = new Node(gameboard.context, node_8_loc);
    var node_9 = new Node(gameboard.context, node_9_loc);
    var node_10 = new Node(gameboard.context, node_10_loc);
    var node_11 = new Node(gameboard.context, node_11_loc);
    var node_12 = new Node(gameboard.context, node_12_loc);
    var node_13 = new Node(gameboard.context, node_13_loc);
    var node_14 = new Node(gameboard.context, node_14_loc);
    var node_15 = new Node(gameboard.context, node_15_loc);
    var node_16 = new Node(gameboard.context, node_16_loc);
    var node_17 = new Node(gameboard.context, node_17_loc);
    var node_18 = new Node(gameboard.context, node_18_loc);
    var node_19 = new Node(gameboard.context, node_19_loc);
    var node_20 = new Node(gameboard.context, node_20_loc);
    var node_21 = new Node(gameboard.context, node_21_loc);
    var node_22 = new Node(gameboard.context, node_22_loc);
    var node_23 = new Node(gameboard.context, node_23_loc);
    var node_24 = new Node(gameboard.context, node_24_loc);
    var node_25 = new Node(gameboard.context, node_25_loc);
    var node_26 = new Node(gameboard.context, node_26_loc);
    var node_27 = new Node(gameboard.context, node_27_loc);
    var node_28 = new Node(gameboard.context, node_28_loc);
    var node_29 = new Node(gameboard.context, node_29_loc);
    var node_30 = new Node(gameboard.context, node_30_loc);

    // third connect the nodes, running a connection from A->B will also create the connection from B->A
    node_0.connect(node_1);
    node_0.connect(node_4);
    node_0.connect(node_5);
    node_0.connect(node_6);
    node_1.connect(node_2);
    node_1.connect(node_6);
    node_1.connect(node_7);
    node_2.connect(node_3);
    node_2.connect(node_7);
    node_3.connect(node_8);
    node_3.connect(node_9);
    node_4.connect(node_5);
    node_4.connect(node_10);
    node_4.connect(node_11);
    node_5.connect(node_6);
    node_5.connect(node_10);
    node_5.connect(node_11);
    node_6.connect(node_7);
    node_6.connect(node_11);
    node_6.connect(node_12);
    node_7.connect(node_8);
    node_7.connect(node_12);
    node_7.connect(node_13);
    node_8.connect(node_9);
    node_8.connect(node_14);
    node_8.connect(node_15);
    node_9.connect(node_15);
    node_10.connect(node_11);
    node_10.connect(node_16);
    node_10.connect(node_17);
    node_11.connect(node_12);
    node_11.connect(node_17);
    node_12.connect(node_13);
    node_12.connect(node_18);
    node_12.connect(node_19);
    node_13.connect(node_14);
    node_13.connect(node_19);
    node_14.connect(node_15);
    node_14.connect(node_19);
    node_14.connect(node_20);
    node_14.connect(node_21);
    node_15.connect(node_20);
    node_15.connect(node_21);
    node_16.connect(node_17);
    node_16.connect(node_22);
    node_17.connect(node_18);
    node_17.connect(node_22);
    node_17.connect(node_23);
    node_18.connect(node_19);
    node_18.connect(node_24);
    node_18.connect(node_25);
    node_19.connect(node_20);
    node_19.connect(node_25);
    node_20.connect(node_21);
    node_20.connect(node_26);
    node_21.connect(node_26);
    node_22.connect(node_23);
    node_23.connect(node_24);
    node_23.connect(node_27);
    node_24.connect(node_25);
    node_24.connect(node_27);
    node_24.connect(node_28);
    node_25.connect(node_26);
    node_25.connect(node_29);
    node_26.connect(node_29);
    node_26.connect(node_30);
    node_27.connect(node_28);
    node_28.connect(node_29);
    node_29.connect(node_30);

    // fourth add the nodes to the network
    networks.nodes = [node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9, node_10, node_11, node_12, node_13, node_14, node_15, node_16, node_17, node_18, node_19, node_20, node_21, node_22, node_23, node_24, node_25, node_26, node_27, node_28, node_29, node_30];

    //  fifth set the game parameters
    networks.observationNodes = [30, 13, 8];
    networks.optimalHops = 4;
    networks.maxRounds = 3;
}


// [autogenerated] Kilshin network - Large
function generatePuzzleKilshinLarge() {
    // first record the location of each node, as an x% y% of the canvas
    var node_0_loc = [0.08174302203951923, 0.22405438265601202];
    var node_1_loc = [0.1407761470106606, 0.33817958773081036];
    var node_2_loc = [0.11066380833279767, 0.43869642595403047];
    var node_3_loc = [0.12717505730670958, 0.6355043696255741];
    var node_4_loc = [0.1210346723592086, 0.6499987764568462];
    var node_5_loc = [0.2194485474905332, 0.18154750593247188];
    var node_6_loc = [0.19157682720904767, 0.35946951933335947];
    var node_7_loc = [0.2287936623495556, 0.4697775599672729];
    var node_8_loc = [0.2227402965398237, 0.5371817685235724];
    var node_9_loc = [0.2301064201295059, 0.6936162891652303];
    var node_10_loc = [0.16820233132474485, 0.8166467729662554];
    var node_11_loc = [0.3286237837200243, 0.048565025733208554];
    var node_12_loc = [0.29710405043344995, 0.19363931182640823];
    var node_13_loc = [0.34651605454557044, 0.2816655362618457];
    var node_14_loc = [0.32672670971114226, 0.4137511239281813];
    var node_15_loc = [0.3425030315205629, 0.5486227587345184];
    var node_16_loc = [0.2940922674480761, 0.70379126497716];
    var node_17_loc = [0.3221365372991015, 0.7631879522159682];
    var node_18_loc = [0.3006986744937748, 0.8632057430749288];
    var node_19_loc = [0.4205241882912332, 0.07913005815077967];
    var node_20_loc = [0.4201047890230006, 0.2394190681940891];
    var node_21_loc = [0.4805334596275788, 0.28224429001302603];
    var node_22_loc = [0.4589365816730082, 0.4596098571343142];
    var node_23_loc = [0.41209293489366033, 0.5547834994995164];
    var node_24_loc = [0.4817924624609061, 0.7004732607688001];
    var node_25_loc = [0.45672036197400584, 0.7967671598432845];
    var node_26_loc = [0.42926562741214797, 0.9449325737632824];
    var node_27_loc = [0.6381501462422249, 0.07894832377119916];
    var node_28_loc = [0.5377627479374183, 0.2811750737620399];
    var node_29_loc = [0.5448335711696936, 0.3069382032851761];
    var node_30_loc = [0.5550101571014386, 0.4597859275342167];
    var node_31_loc = [0.5849292086485386, 0.5496178327589742];
    var node_32_loc = [0.5532489412142662, 0.6581185054223759];
    var node_33_loc = [0.5393684856630672, 0.806987424630831];
    var node_34_loc = [0.5761073077676284, 0.8593635101240837];
    var node_35_loc = [0.6258823459985511, 0.11353339859003611];
    var node_36_loc = [0.6663479140008597, 0.14057725078201858];
    var node_37_loc = [0.6314695145893822, 0.34085166731658817];
    var node_38_loc = [0.6772151838481543, 0.4110466764020542];
    var node_39_loc = [0.687960423769193, 0.5681186272943014];
    var node_40_loc = [0.6528619844885706, 0.6935142987766926];
    var node_41_loc = [0.705326944286734, 0.8035402612073751];
    var node_42_loc = [0.6560817074472451, 0.9042033366511328];
    var node_43_loc = [0.8071268860301412, 0.10178488599822458];
    var node_44_loc = [0.7740520672390745, 0.1832039415364769];
    var node_45_loc = [0.7714270553740321, 0.3161258175011904];
    var node_46_loc = [0.8582596115248684, 0.43042900916832916];
    var node_47_loc = [0.8194935725212718, 0.6281790330033556];
    var node_48_loc = [0.79063468118235, 0.6691417043273702];
    var node_49_loc = [0.7659645361894227, 0.7950436727354343];
    var node_50_loc = [0.7883175549719234, 0.8581943473367631];
    var node_51_loc = [0.8583505415351252, 0.22081891891501443];
    var node_52_loc = [0.8945371104551799, 0.3224927951008959];
    var node_53_loc = [0.8841590663108533, 0.4377089176974083];
    var node_54_loc = [0.9556241039088859, 0.5441981914697513];
    var node_55_loc = [0.8981447379945758, 0.6486662657508179];
    var node_56_loc = [0.8774679864060847, 0.7983262399091844];

    // second create the node objects
    var node_0 = new Node(gameboard.context, node_0_loc);
    var node_1 = new Node(gameboard.context, node_1_loc);
    var node_2 = new Node(gameboard.context, node_2_loc);
    var node_3 = new Node(gameboard.context, node_3_loc);
    var node_4 = new Node(gameboard.context, node_4_loc);
    var node_5 = new Node(gameboard.context, node_5_loc);
    var node_6 = new Node(gameboard.context, node_6_loc);
    var node_7 = new Node(gameboard.context, node_7_loc);
    var node_8 = new Node(gameboard.context, node_8_loc);
    var node_9 = new Node(gameboard.context, node_9_loc);
    var node_10 = new Node(gameboard.context, node_10_loc);
    var node_11 = new Node(gameboard.context, node_11_loc);
    var node_12 = new Node(gameboard.context, node_12_loc);
    var node_13 = new Node(gameboard.context, node_13_loc);
    var node_14 = new Node(gameboard.context, node_14_loc);
    var node_15 = new Node(gameboard.context, node_15_loc);
    var node_16 = new Node(gameboard.context, node_16_loc);
    var node_17 = new Node(gameboard.context, node_17_loc);
    var node_18 = new Node(gameboard.context, node_18_loc);
    var node_19 = new Node(gameboard.context, node_19_loc);
    var node_20 = new Node(gameboard.context, node_20_loc);
    var node_21 = new Node(gameboard.context, node_21_loc);
    var node_22 = new Node(gameboard.context, node_22_loc);
    var node_23 = new Node(gameboard.context, node_23_loc);
    var node_24 = new Node(gameboard.context, node_24_loc);
    var node_25 = new Node(gameboard.context, node_25_loc);
    var node_26 = new Node(gameboard.context, node_26_loc);
    var node_27 = new Node(gameboard.context, node_27_loc);
    var node_28 = new Node(gameboard.context, node_28_loc);
    var node_29 = new Node(gameboard.context, node_29_loc);
    var node_30 = new Node(gameboard.context, node_30_loc);
    var node_31 = new Node(gameboard.context, node_31_loc);
    var node_32 = new Node(gameboard.context, node_32_loc);
    var node_33 = new Node(gameboard.context, node_33_loc);
    var node_34 = new Node(gameboard.context, node_34_loc);
    var node_35 = new Node(gameboard.context, node_35_loc);
    var node_36 = new Node(gameboard.context, node_36_loc);
    var node_37 = new Node(gameboard.context, node_37_loc);
    var node_38 = new Node(gameboard.context, node_38_loc);
    var node_39 = new Node(gameboard.context, node_39_loc);
    var node_40 = new Node(gameboard.context, node_40_loc);
    var node_41 = new Node(gameboard.context, node_41_loc);
    var node_42 = new Node(gameboard.context, node_42_loc);
    var node_43 = new Node(gameboard.context, node_43_loc);
    var node_44 = new Node(gameboard.context, node_44_loc);
    var node_45 = new Node(gameboard.context, node_45_loc);
    var node_46 = new Node(gameboard.context, node_46_loc);
    var node_47 = new Node(gameboard.context, node_47_loc);
    var node_48 = new Node(gameboard.context, node_48_loc);
    var node_49 = new Node(gameboard.context, node_49_loc);
    var node_50 = new Node(gameboard.context, node_50_loc);
    var node_51 = new Node(gameboard.context, node_51_loc);
    var node_52 = new Node(gameboard.context, node_52_loc);
    var node_53 = new Node(gameboard.context, node_53_loc);
    var node_54 = new Node(gameboard.context, node_54_loc);
    var node_55 = new Node(gameboard.context, node_55_loc);
    var node_56 = new Node(gameboard.context, node_56_loc);

    // third connect the nodes, running a connection from A->B will also create the connection from B->A
    node_0.connect(node_1);
    node_0.connect(node_5);
    node_1.connect(node_2);
    node_1.connect(node_6);
    node_1.connect(node_7);
    node_2.connect(node_7);
    node_3.connect(node_4);
    node_3.connect(node_8);
    node_3.connect(node_9);
    node_4.connect(node_8);
    node_4.connect(node_9);
    node_5.connect(node_6);
    node_5.connect(node_12);
    node_6.connect(node_7);
    node_6.connect(node_13);
    node_7.connect(node_14);
    node_8.connect(node_9);
    node_8.connect(node_15);
    node_8.connect(node_16);
    node_9.connect(node_10);
    node_9.connect(node_16);
    node_10.connect(node_17);
    node_11.connect(node_12);
    node_11.connect(node_19);
    node_12.connect(node_13);
    node_13.connect(node_14);
    node_14.connect(node_22);
    node_15.connect(node_16);
    node_15.connect(node_23);
    node_16.connect(node_17);
    node_17.connect(node_18);
    node_18.connect(node_26);
    node_19.connect(node_20);
    node_20.connect(node_21);
    node_20.connect(node_28);
    node_21.connect(node_22);
    node_21.connect(node_28);
    node_21.connect(node_29);
    node_22.connect(node_30);
    node_23.connect(node_24);
    node_23.connect(node_31);
    node_23.connect(node_32);
    node_24.connect(node_25);
    node_24.connect(node_32);
    node_24.connect(node_33);
    node_25.connect(node_26);
    node_25.connect(node_33);
    node_27.connect(node_28);
    node_27.connect(node_35);
    node_27.connect(node_36);
    node_28.connect(node_29);
    node_28.connect(node_36);
    node_29.connect(node_30);
    node_29.connect(node_37);
    node_29.connect(node_38);
    node_30.connect(node_31);
    node_30.connect(node_38);
    node_31.connect(node_32);
    node_31.connect(node_38);
    node_31.connect(node_39);
    node_32.connect(node_33);
    node_32.connect(node_39);
    node_32.connect(node_40);
    node_33.connect(node_34);
    node_33.connect(node_41);
    node_34.connect(node_42);
    node_35.connect(node_36);
    node_35.connect(node_43);
    node_36.connect(node_43);
    node_36.connect(node_44);
    node_37.connect(node_38);
    node_37.connect(node_45);
    node_38.connect(node_39);
    node_39.connect(node_47);
    node_40.connect(node_41);
    node_40.connect(node_48);
    node_41.connect(node_42);
    node_42.connect(node_50);
    node_43.connect(node_44);
    node_44.connect(node_45);
    node_44.connect(node_51);
    node_45.connect(node_46);
    node_45.connect(node_52);
    node_46.connect(node_53);
    node_47.connect(node_48);
    node_47.connect(node_55);
    node_48.connect(node_55);
    node_49.connect(node_50);
    node_49.connect(node_56);
    node_52.connect(node_53);
    node_53.connect(node_54);
    node_54.connect(node_55);
    node_55.connect(node_56);

    // fourth add the nodes to the network
    networks.nodes = [node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9, node_10, node_11, node_12, node_13, node_14, node_15, node_16, node_17, node_18, node_19, node_20, node_21, node_22, node_23, node_24, node_25, node_26, node_27, node_28, node_29, node_30, node_31, node_32, node_33, node_34, node_35, node_36, node_37, node_38, node_39, node_40, node_41, node_42, node_43, node_44, node_45, node_46, node_47, node_48, node_49, node_50, node_51, node_52, node_53, node_54, node_55, node_56];

    //  fifth set the game parameters
    networks.observationNodes = [10, 50, 46];
    networks.optimalHops = 7;
    networks.maxRounds = 3;
}


// [autogenerated] Kilshin network - Semilong
function generatePuzzleKilshinSemilong() {
    // first record the location of each node, as an x% y% of the canvas
    var node_0_loc = [0.09086448404396129, 0.26144165158021404];
    var node_1_loc = [0.0947309312616535, 0.4537643639594623];
    var node_2_loc = [0.08795761147503638, 0.5661702838278545];
    var node_3_loc = [0.11729781512970358, 0.7137402274406248];
    var node_4_loc = [0.2540132323443864, 0.12377150851434827];
    var node_5_loc = [0.25682693719536354, 0.22710199996557862];
    var node_6_loc = [0.23401418601044902, 0.4178200007807978];
    var node_7_loc = [0.2300176225235937, 0.5476484321666408];
    var node_8_loc = [0.22417899254279577, 0.755036386785564];
    var node_9_loc = [0.27738276742055595, 0.8733350439506915];
    var node_10_loc = [0.3904380896332602, 0.14315937347006655];
    var node_11_loc = [0.3605124426958023, 0.284736156685938];
    var node_12_loc = [0.399027655954692, 0.3990781481521572];
    var node_13_loc = [0.37821062633652996, 0.591960462223065];
    var node_14_loc = [0.4414765800540386, 0.7289589892912997];
    var node_15_loc = [0.5818467815253766, 0.12507028026755446];
    var node_16_loc = [0.5792880060176977, 0.20907683521140846];
    var node_17_loc = [0.5770459133103045, 0.3995733692424477];
    var node_18_loc = [0.5240520298774929, 0.5673480964649534];
    var node_19_loc = [0.5248380842242227, 0.7539157507710029];
    var node_20_loc = [0.515589164727059, 0.8272114299430497];
    var node_21_loc = [0.7857128446792816, 0.12082926008359761];
    var node_22_loc = [0.7723098027204428, 0.2478025403147593];
    var node_23_loc = [0.7990342672769257, 0.41141128564640617];
    var node_24_loc = [0.735313609326682, 0.5324365326119416];
    var node_25_loc = [0.7671329553452103, 0.7330171620378955];
    var node_26_loc = [0.8702133874092334, 0.24074345773387967];
    var node_27_loc = [0.9258916057375806, 0.40382621420298875];
    var node_28_loc = [0.9339620926300154, 0.6995472891132594];

    // second create the node objects
    var node_0 = new Node(gameboard.context, node_0_loc);
    var node_1 = new Node(gameboard.context, node_1_loc);
    var node_2 = new Node(gameboard.context, node_2_loc);
    var node_3 = new Node(gameboard.context, node_3_loc);
    var node_4 = new Node(gameboard.context, node_4_loc);
    var node_5 = new Node(gameboard.context, node_5_loc);
    var node_6 = new Node(gameboard.context, node_6_loc);
    var node_7 = new Node(gameboard.context, node_7_loc);
    var node_8 = new Node(gameboard.context, node_8_loc);
    var node_9 = new Node(gameboard.context, node_9_loc);
    var node_10 = new Node(gameboard.context, node_10_loc);
    var node_11 = new Node(gameboard.context, node_11_loc);
    var node_12 = new Node(gameboard.context, node_12_loc);
    var node_13 = new Node(gameboard.context, node_13_loc);
    var node_14 = new Node(gameboard.context, node_14_loc);
    var node_15 = new Node(gameboard.context, node_15_loc);
    var node_16 = new Node(gameboard.context, node_16_loc);
    var node_17 = new Node(gameboard.context, node_17_loc);
    var node_18 = new Node(gameboard.context, node_18_loc);
    var node_19 = new Node(gameboard.context, node_19_loc);
    var node_20 = new Node(gameboard.context, node_20_loc);
    var node_21 = new Node(gameboard.context, node_21_loc);
    var node_22 = new Node(gameboard.context, node_22_loc);
    var node_23 = new Node(gameboard.context, node_23_loc);
    var node_24 = new Node(gameboard.context, node_24_loc);
    var node_25 = new Node(gameboard.context, node_25_loc);
    var node_26 = new Node(gameboard.context, node_26_loc);
    var node_27 = new Node(gameboard.context, node_27_loc);
    var node_28 = new Node(gameboard.context, node_28_loc);

    // third connect the nodes, running a connection from A->B will also create the connection from B->A
    node_0.connect(node_11);
    node_1.connect(node_8);
    node_2.connect(node_5);
    node_2.connect(node_7);
    node_2.connect(node_9);
    node_2.connect(node_13);
    node_3.connect(node_9);
    node_4.connect(node_5);
    node_4.connect(node_6);
    node_4.connect(node_7);
    node_6.connect(node_8);
    node_6.connect(node_10);
    node_6.connect(node_11);
    node_6.connect(node_14);
    node_8.connect(node_20);
    node_9.connect(node_13);
    node_9.connect(node_19);
    node_11.connect(node_15);
    node_12.connect(node_13);
    node_12.connect(node_14);
    node_12.connect(node_17);
    node_12.connect(node_22);
    node_12.connect(node_23);
    node_13.connect(node_25);
    node_14.connect(node_17);
    node_14.connect(node_20);
    node_14.connect(node_24);
    node_14.connect(node_25);
    node_15.connect(node_23);
    node_16.connect(node_24);
    node_17.connect(node_26);
    node_17.connect(node_28);
    node_18.connect(node_22);
    node_18.connect(node_23);
    node_18.connect(node_25);
    node_18.connect(node_28);
    node_19.connect(node_24);
    node_19.connect(node_25);
    node_21.connect(node_23);
    node_21.connect(node_27);
    node_22.connect(node_27);
    node_24.connect(node_25);

    // fourth add the nodes to the network
    networks.nodes = [node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9, node_10, node_11, node_12, node_13, node_14, node_15, node_16, node_17, node_18, node_19, node_20, node_21, node_22, node_23, node_24, node_25, node_26, node_27, node_28];

    //  fifth set the game parameters
    networks.observationNodes = [12, 0, 16];
    networks.optimalHops = 4;
    networks.maxRounds = 3;
}


// [autogenerated] Kilshin network - Shortcut
function generatePuzzleKilshinShortcut() {
    // first record the location of each node, as an x% y% of the canvas
    var node_0_loc = [0.1148632889129601, 0.2841785722636575];
    var node_1_loc = [0.16142997292057493, 0.42245595370940325];
    var node_2_loc = [0.05238885882876406, 0.6129855661650195];
    var node_3_loc = [0.1422972356786606, 0.7462272250190825];
    var node_4_loc = [0.2752302876404887, 0.13281045174945932];
    var node_5_loc = [0.21870942956255052, 0.21484845511563463];
    var node_6_loc = [0.24560348029381535, 0.43650668453916114];
    var node_7_loc = [0.22761252073328087, 0.5638994500249787];
    var node_8_loc = [0.23881471239622087, 0.7415932503326342];
    var node_9_loc = [0.23588642903567877, 0.8936885475649899];
    var node_10_loc = [0.45511287269148126, 0.13219654742052028];
    var node_11_loc = [0.36395205467040376, 0.22612000354364786];
    var node_12_loc = [0.4033593917186711, 0.3988723914121652];
    var node_13_loc = [0.3784574838436904, 0.5384214434097477];
    var node_14_loc = [0.46800457524661776, 0.7568287237943525];
    var node_15_loc = [0.37469378659992075, 0.9147814500604018];
    var node_16_loc = [0.6180578922948134, 0.17807416750025673];
    var node_17_loc = [0.5896823023844592, 0.42463242266433576];
    var node_18_loc = [0.5562500279095879, 0.5824059418307294];
    var node_19_loc = [0.552204884052071, 0.7392018596763615];
    var node_20_loc = [0.6272057825474385, 0.9142309159798528];
    var node_21_loc = [0.7222108885993433, 0.07172809954075135];
    var node_22_loc = [0.8265538393215334, 0.21187744801105726];
    var node_23_loc = [0.7404257875096087, 0.3989350824729904];
    var node_24_loc = [0.7454553382496325, 0.588916425367501];
    var node_25_loc = [0.778749056320187, 0.7295546852033862];
    var node_26_loc = [0.9005273274405518, 0.26484737056351293];
    var node_27_loc = [0.9739307521662469, 0.41169398974264765];
    var node_28_loc = [0.8703516681278912, 0.5534500329320552];
    var node_29_loc = [0.9484381563304838, 0.7191985449840927];

    // second create the node objects
    var node_0 = new Node(gameboard.context, node_0_loc);
    var node_1 = new Node(gameboard.context, node_1_loc);
    var node_2 = new Node(gameboard.context, node_2_loc);
    var node_3 = new Node(gameboard.context, node_3_loc);
    var node_4 = new Node(gameboard.context, node_4_loc);
    var node_5 = new Node(gameboard.context, node_5_loc);
    var node_6 = new Node(gameboard.context, node_6_loc);
    var node_7 = new Node(gameboard.context, node_7_loc);
    var node_8 = new Node(gameboard.context, node_8_loc);
    var node_9 = new Node(gameboard.context, node_9_loc);
    var node_10 = new Node(gameboard.context, node_10_loc);
    var node_11 = new Node(gameboard.context, node_11_loc);
    var node_12 = new Node(gameboard.context, node_12_loc);
    var node_13 = new Node(gameboard.context, node_13_loc);
    var node_14 = new Node(gameboard.context, node_14_loc);
    var node_15 = new Node(gameboard.context, node_15_loc);
    var node_16 = new Node(gameboard.context, node_16_loc);
    var node_17 = new Node(gameboard.context, node_17_loc);
    var node_18 = new Node(gameboard.context, node_18_loc);
    var node_19 = new Node(gameboard.context, node_19_loc);
    var node_20 = new Node(gameboard.context, node_20_loc);
    var node_21 = new Node(gameboard.context, node_21_loc);
    var node_22 = new Node(gameboard.context, node_22_loc);
    var node_23 = new Node(gameboard.context, node_23_loc);
    var node_24 = new Node(gameboard.context, node_24_loc);
    var node_25 = new Node(gameboard.context, node_25_loc);
    var node_26 = new Node(gameboard.context, node_26_loc);
    var node_27 = new Node(gameboard.context, node_27_loc);
    var node_28 = new Node(gameboard.context, node_28_loc);
    var node_29 = new Node(gameboard.context, node_29_loc);

    // third connect the nodes, running a connection from A->B will also create the connection from B->A
    node_0.connect(node_1);
    node_0.connect(node_5);
    node_0.connect(node_16);
    node_2.connect(node_3);
    node_3.connect(node_9);
    node_4.connect(node_5);
    node_4.connect(node_10);
    node_5.connect(node_6);
    node_5.connect(node_10);
    node_5.connect(node_11);
    node_5.connect(node_13);
    node_6.connect(node_7);
    node_6.connect(node_11);
    node_7.connect(node_12);
    node_8.connect(node_9);
    node_8.connect(node_15);
    node_9.connect(node_15);
    node_10.connect(node_11);
    node_10.connect(node_20);
    node_11.connect(node_12);
    node_11.connect(node_16);
    node_12.connect(node_13);
    node_12.connect(node_17);
    node_12.connect(node_18);
    node_13.connect(node_14);
    node_14.connect(node_15);
    node_14.connect(node_18);
    node_14.connect(node_19);
    node_14.connect(node_20);
    node_15.connect(node_19);
    node_15.connect(node_20);
    node_16.connect(node_17);
    node_16.connect(node_21);
    node_17.connect(node_23);
    node_18.connect(node_19);
    node_18.connect(node_24);
    node_19.connect(node_25);
    node_22.connect(node_23);
    node_22.connect(node_26);
    node_23.connect(node_24);
    node_23.connect(node_26);
    node_23.connect(node_27);
    node_24.connect(node_25);
    node_24.connect(node_28);
    node_25.connect(node_28);
    node_26.connect(node_27);
    node_27.connect(node_28);
    node_28.connect(node_29);

    // fourth add the nodes to the network
    networks.nodes = [node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9, node_10, node_11, node_12, node_13, node_14, node_15, node_16, node_17, node_18, node_19, node_20, node_21, node_22, node_23, node_24, node_25, node_26, node_27, node_28, node_29];

    //  fifth set the game parameters
    networks.observationNodes = [1, 24, 23];
    networks.optimalHops = 5;
    networks.maxRounds = 3;
}


// [autogenerated] Kilshin network - Small
function generatePuzzleKilshinSmall() {
    // first record the location of each node, as an x% y% of the canvas
    var node_0_loc = [0.14006469267765942, 0.32347890213961206];
    var node_1_loc = [0.14351593325788947, 0.5728977950955215];
    var node_2_loc = [0.3006814101377416, 0.10023580134052362];
    var node_3_loc = [0.37475188629201, 0.36579013403165733];
    var node_4_loc = [0.31704152813435754, 0.5922201769663865];
    var node_5_loc = [0.38939170620523816, 0.8244988509067995];
    var node_6_loc = [0.6233069277829077, 0.4168474562379367];
    var node_7_loc = [0.5301478060466941, 0.6201029123135897];
    var node_8_loc = [0.5867794626639056, 0.8498583324315028];
    var node_9_loc = [0.8807889078954844, 0.3805001545852771];
    var node_10_loc = [0.8371389194042708, 0.5633031259753779];

    // second create the node objects
    var node_0 = new Node(gameboard.context, node_0_loc);
    var node_1 = new Node(gameboard.context, node_1_loc);
    var node_2 = new Node(gameboard.context, node_2_loc);
    var node_3 = new Node(gameboard.context, node_3_loc);
    var node_4 = new Node(gameboard.context, node_4_loc);
    var node_5 = new Node(gameboard.context, node_5_loc);
    var node_6 = new Node(gameboard.context, node_6_loc);
    var node_7 = new Node(gameboard.context, node_7_loc);
    var node_8 = new Node(gameboard.context, node_8_loc);
    var node_9 = new Node(gameboard.context, node_9_loc);
    var node_10 = new Node(gameboard.context, node_10_loc);

    // third connect the nodes, running a connection from A->B will also create the connection from B->A
    node_0.connect(node_3);
    node_1.connect(node_4);
    node_2.connect(node_3);
    node_3.connect(node_4);
    node_4.connect(node_5);
    node_4.connect(node_7);
    node_5.connect(node_8);
    node_6.connect(node_7);
    node_6.connect(node_9);
    node_7.connect(node_8);
    node_9.connect(node_10);

    // fourth add the nodes to the network
    networks.nodes = [node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9, node_10];

    //  fifth set the game parameters
    networks.observationNodes = [1, 6, 4];
    networks.optimalHops = 3;
    networks.maxRounds = 3;
}


// [autogenerated] Kilshin network - Sparse
function generatePuzzleKilshinSparse() {
    // first record the location of each node, as an x% y% of the canvas
    var node_0_loc = [0.1148632889129601, 0.2841785722636575];
    var node_1_loc = [0.16142997292057493, 0.42245595370940325];
    var node_2_loc = [0.05238885882876406, 0.6129855661650195];
    var node_3_loc = [0.1422972356786606, 0.7462272250190825];
    var node_4_loc = [0.2752302876404887, 0.13281045174945932];
    var node_5_loc = [0.21870942956255052, 0.21484845511563463];
    var node_6_loc = [0.24560348029381535, 0.43650668453916114];
    var node_7_loc = [0.22761252073328087, 0.5638994500249787];
    var node_8_loc = [0.23881471239622087, 0.7415932503326342];
    var node_9_loc = [0.23588642903567877, 0.8936885475649899];
    var node_10_loc = [0.45511287269148126, 0.13219654742052028];
    var node_11_loc = [0.36395205467040376, 0.22612000354364786];
    var node_12_loc = [0.4033593917186711, 0.3988723914121652];
    var node_13_loc = [0.3784574838436904, 0.5384214434097477];
    var node_14_loc = [0.46800457524661776, 0.7568287237943525];
    var node_15_loc = [0.37469378659992075, 0.9147814500604018];
    var node_16_loc = [0.6180578922948134, 0.17807416750025673];
    var node_17_loc = [0.5896823023844592, 0.42463242266433576];
    var node_18_loc = [0.5562500279095879, 0.5824059418307294];
    var node_19_loc = [0.552204884052071, 0.7392018596763615];
    var node_20_loc = [0.6272057825474385, 0.9142309159798528];
    var node_21_loc = [0.7222108885993433, 0.07172809954075135];
    var node_22_loc = [0.8265538393215334, 0.21187744801105726];
    var node_23_loc = [0.7404257875096087, 0.3989350824729904];
    var node_24_loc = [0.7454553382496325, 0.588916425367501];
    var node_25_loc = [0.778749056320187, 0.7295546852033862];
    var node_26_loc = [0.9005273274405518, 0.26484737056351293];
    var node_27_loc = [0.9539307521662469, 0.41169398974264765];
    var node_28_loc = [0.8703516681278912, 0.5534500329320552];
    var node_29_loc = [0.9484381563304838, 0.7191985449840927];

    // second create the node objects
    var node_0 = new Node(gameboard.context, node_0_loc);
    var node_1 = new Node(gameboard.context, node_1_loc);
    var node_2 = new Node(gameboard.context, node_2_loc);
    var node_3 = new Node(gameboard.context, node_3_loc);
    var node_4 = new Node(gameboard.context, node_4_loc);
    var node_5 = new Node(gameboard.context, node_5_loc);
    var node_6 = new Node(gameboard.context, node_6_loc);
    var node_7 = new Node(gameboard.context, node_7_loc);
    var node_8 = new Node(gameboard.context, node_8_loc);
    var node_9 = new Node(gameboard.context, node_9_loc);
    var node_10 = new Node(gameboard.context, node_10_loc);
    var node_11 = new Node(gameboard.context, node_11_loc);
    var node_12 = new Node(gameboard.context, node_12_loc);
    var node_13 = new Node(gameboard.context, node_13_loc);
    var node_14 = new Node(gameboard.context, node_14_loc);
    var node_15 = new Node(gameboard.context, node_15_loc);
    var node_16 = new Node(gameboard.context, node_16_loc);
    var node_17 = new Node(gameboard.context, node_17_loc);
    var node_18 = new Node(gameboard.context, node_18_loc);
    var node_19 = new Node(gameboard.context, node_19_loc);
    var node_20 = new Node(gameboard.context, node_20_loc);
    var node_21 = new Node(gameboard.context, node_21_loc);
    var node_22 = new Node(gameboard.context, node_22_loc);
    var node_23 = new Node(gameboard.context, node_23_loc);
    var node_24 = new Node(gameboard.context, node_24_loc);
    var node_25 = new Node(gameboard.context, node_25_loc);
    var node_26 = new Node(gameboard.context, node_26_loc);
    var node_27 = new Node(gameboard.context, node_27_loc);
    var node_28 = new Node(gameboard.context, node_28_loc);
    var node_29 = new Node(gameboard.context, node_29_loc);

    // third connect the nodes, running a connection from A->B will also create the connection from B->A
    node_0.connect(node_1);
    node_0.connect(node_5);
    node_2.connect(node_3);
    node_3.connect(node_9);
    node_4.connect(node_5);
    node_4.connect(node_10);
    node_5.connect(node_6);
    node_5.connect(node_10);
    node_5.connect(node_11);
    node_6.connect(node_7);
    node_6.connect(node_11);
    node_7.connect(node_12);
    node_8.connect(node_9);
    node_8.connect(node_15);
    node_9.connect(node_15);
    node_10.connect(node_11);
    node_11.connect(node_12);
    node_11.connect(node_16);
    node_12.connect(node_13);
    node_12.connect(node_17);
    node_12.connect(node_18);
    node_13.connect(node_14);
    node_14.connect(node_15);
    node_14.connect(node_18);
    node_14.connect(node_19);
    node_14.connect(node_20);
    node_15.connect(node_19);
    node_15.connect(node_20);
    node_16.connect(node_17);
    node_16.connect(node_21);
    node_17.connect(node_23);
    node_18.connect(node_19);
    node_18.connect(node_24);
    node_19.connect(node_25);
    node_22.connect(node_23);
    node_22.connect(node_26);
    node_23.connect(node_24);
    node_23.connect(node_26);
    node_23.connect(node_27);
    node_24.connect(node_25);
    node_24.connect(node_28);
    node_25.connect(node_28);
    node_26.connect(node_27);
    node_27.connect(node_28);
    node_28.connect(node_29);

    // fourth add the nodes to the network
    networks.nodes = [node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9, node_10, node_11, node_12, node_13, node_14, node_15, node_16, node_17, node_18, node_19, node_20, node_21, node_22, node_23, node_24, node_25, node_26, node_27, node_28, node_29];

    //  fifth set the game parameters
    networks.observationNodes = [3, 18, 7];
    networks.optimalHops = 6;
    networks.maxRounds = 3;
}


// [autogenerated] Kilshin network - Tree
function generatePuzzleKilshinTree() {
    // first record the location of each node, as an x% y% of the canvas
    var node_0_loc = [0.09760834602026522, 0.2467845861042649];
    var node_1_loc = [0.14511550672952897, 0.3897320977802634];
    var node_2_loc = [0.058919164869187184, 0.5322420980246029];
    var node_3_loc = [0.13914922238802221, 0.7636804516366898];
    var node_4_loc = [0.21655878642825163, 0.10359984692524107];
    var node_5_loc = [0.27458592724673236, 0.19898628658676243];
    var node_6_loc = [0.22652412089121848, 0.4120853070928266];
    var node_7_loc = [0.21749654493895468, 0.562178929765678];
    var node_8_loc = [0.2455646940586921, 0.7399341852338205];
    var node_9_loc = [0.25738593152160805, 0.9216807123157172];
    var node_10_loc = [0.4152704027164105, 0.08511442716927078];
    var node_11_loc = [0.34122088994204447, 0.24974624455184344];
    var node_12_loc = [0.3915786276188391, 0.4231641681760175];
    var node_13_loc = [0.38260551027398587, 0.5684478463044337];
    var node_14_loc = [0.4012093914829035, 0.7209192506715758];
    var node_15_loc = [0.40304713755553073, 0.8825673752101596];
    var node_16_loc = [0.5606844682868986, 0.12042550507673663];
    var node_17_loc = [0.5964736684191215, 0.19841075510629202];
    var node_18_loc = [0.6467441616638935, 0.4430270123671901];
    var node_19_loc = [0.5165083339897311, 0.6081188013303951];
    var node_20_loc = [0.558407057721125, 0.7252806810772887];
    var node_21_loc = [0.5650349167155481, 0.8353956094790811];
    var node_22_loc = [0.7365345241244307, 0.12160461671575133];
    var node_23_loc = [0.7511137081667025, 0.24689166696728457];
    var node_24_loc = [0.8016519893012957, 0.3676557789147757];
    var node_25_loc = [0.739812240244089, 0.5555296134602589];
    var node_26_loc = [0.7424932232827374, 0.7257180820098511];
    var node_27_loc = [0.887485640702675, 0.26944601634723664];
    var node_28_loc = [0.9137180318363167, 0.41342874830552795];
    var node_29_loc = [0.9218312069866897, 0.5869895619645998];
    var node_30_loc = [0.9339010846001771, 0.7442367153648258];

    // second create the node objects
    var node_0 = new Node(gameboard.context, node_0_loc);
    var node_1 = new Node(gameboard.context, node_1_loc);
    var node_2 = new Node(gameboard.context, node_2_loc);
    var node_3 = new Node(gameboard.context, node_3_loc);
    var node_4 = new Node(gameboard.context, node_4_loc);
    var node_5 = new Node(gameboard.context, node_5_loc);
    var node_6 = new Node(gameboard.context, node_6_loc);
    var node_7 = new Node(gameboard.context, node_7_loc);
    var node_8 = new Node(gameboard.context, node_8_loc);
    var node_9 = new Node(gameboard.context, node_9_loc);
    var node_10 = new Node(gameboard.context, node_10_loc);
    var node_11 = new Node(gameboard.context, node_11_loc);
    var node_12 = new Node(gameboard.context, node_12_loc);
    var node_13 = new Node(gameboard.context, node_13_loc);
    var node_14 = new Node(gameboard.context, node_14_loc);
    var node_15 = new Node(gameboard.context, node_15_loc);
    var node_16 = new Node(gameboard.context, node_16_loc);
    var node_17 = new Node(gameboard.context, node_17_loc);
    var node_18 = new Node(gameboard.context, node_18_loc);
    var node_19 = new Node(gameboard.context, node_19_loc);
    var node_20 = new Node(gameboard.context, node_20_loc);
    var node_21 = new Node(gameboard.context, node_21_loc);
    var node_22 = new Node(gameboard.context, node_22_loc);
    var node_23 = new Node(gameboard.context, node_23_loc);
    var node_24 = new Node(gameboard.context, node_24_loc);
    var node_25 = new Node(gameboard.context, node_25_loc);
    var node_26 = new Node(gameboard.context, node_26_loc);
    var node_27 = new Node(gameboard.context, node_27_loc);
    var node_28 = new Node(gameboard.context, node_28_loc);
    var node_29 = new Node(gameboard.context, node_29_loc);
    var node_30 = new Node(gameboard.context, node_30_loc);

    // third connect the nodes, running a connection from A->B will also create the connection from B->A
    node_0.connect(node_1);
    node_1.connect(node_2);
    node_1.connect(node_6);
    node_2.connect(node_7);
    node_3.connect(node_8);
    node_4.connect(node_5);
    node_5.connect(node_11);
    node_6.connect(node_12);
    node_7.connect(node_13);
    node_8.connect(node_9);
    node_9.connect(node_15);
    node_10.connect(node_11);
    node_10.connect(node_16);
    node_11.connect(node_12);
    node_13.connect(node_14);
    node_13.connect(node_19);
    node_14.connect(node_15);
    node_14.connect(node_20);
    node_16.connect(node_17);
    node_18.connect(node_19);
    node_18.connect(node_24);
    node_20.connect(node_21);
    node_22.connect(node_23);
    node_23.connect(node_24);
    node_23.connect(node_27);
    node_24.connect(node_25);
    node_26.connect(node_30);
    node_27.connect(node_28);
    node_28.connect(node_29);
    node_29.connect(node_30);

    // fourth add the nodes to the network
    networks.nodes = [node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9, node_10, node_11, node_12, node_13, node_14, node_15, node_16, node_17, node_18, node_19, node_20, node_21, node_22, node_23, node_24, node_25, node_26, node_27, node_28, node_29, node_30];

    //  fifth set the game parameters
    networks.observationNodes = [13, 26, 1];
    networks.optimalHops = 9;
    networks.maxRounds = 3;
}


// [autogenerated] Kilshin network - TreeShortcut
function generatePuzzleKilshinTreeShortcut() {
    // first record the location of each node, as an x% y% of the canvas
    var node_0_loc = [0.06297047268958347, 0.2925832117346408];
    var node_1_loc = [0.11370572142731111, 0.39791821852340953];
    var node_2_loc = [0.06054651873453418, 0.5748326713296745];
    var node_3_loc = [0.08860389885024596, 0.7408937056067306];
    var node_4_loc = [0.2561845224529998, 0.10208268860016798];
    var node_5_loc = [0.2559966950413873, 0.22518826464254527];
    var node_6_loc = [0.24719269197041424, 0.3953831314912189];
    var node_7_loc = [0.2808835755951382, 0.557317529719731];
    var node_8_loc = [0.21425105359539945, 0.7051489267772237];
    var node_9_loc = [0.25361912764064753, 0.8794049495790672];
    var node_10_loc = [0.4348200292044005, 0.10499099135028944];
    var node_11_loc = [0.37517357099556836, 0.236832503776475];
    var node_12_loc = [0.3873910585698654, 0.420542563160695];
    var node_13_loc = [0.38470280688454445, 0.5829248542015645];
    var node_14_loc = [0.46677196517995007, 0.7458911987507539];
    var node_15_loc = [0.3596392237617145, 0.9354144330308658];
    var node_16_loc = [0.5668686812157993, 0.04936049291463059];
    var node_17_loc = [0.6071719385913432, 0.23825439151491867];
    var node_18_loc = [0.5880254586976891, 0.4184940299816363];
    var node_19_loc = [0.5152078713947092, 0.5866455519879957];
    var node_20_loc = [0.5846860847921183, 0.732534841933006];
    var node_21_loc = [0.5913932429777974, 0.9071225555797595];
    var node_22_loc = [0.7049667837001885, 0.10132225747009949];
    var node_23_loc = [0.7515790874655651, 0.20988966134517958];
    var node_24_loc = [0.7291146579709988, 0.3976384161601379];
    var node_25_loc = [0.744220767426006, 0.54990079111298];
    var node_26_loc = [0.7703343893874207, 0.7694194783566337];
    var node_27_loc = [0.8952818004547546, 0.2803161858107547];
    var node_28_loc = [0.9385426675586657, 0.42426912658855837];
    var node_29_loc = [0.9494418422493675, 0.5951548276339684];
    var node_30_loc = [0.915421108165545, 0.7504504202471026];

    // second create the node objects
    var node_0 = new Node(gameboard.context, node_0_loc);
    var node_1 = new Node(gameboard.context, node_1_loc);
    var node_2 = new Node(gameboard.context, node_2_loc);
    var node_3 = new Node(gameboard.context, node_3_loc);
    var node_4 = new Node(gameboard.context, node_4_loc);
    var node_5 = new Node(gameboard.context, node_5_loc);
    var node_6 = new Node(gameboard.context, node_6_loc);
    var node_7 = new Node(gameboard.context, node_7_loc);
    var node_8 = new Node(gameboard.context, node_8_loc);
    var node_9 = new Node(gameboard.context, node_9_loc);
    var node_10 = new Node(gameboard.context, node_10_loc);
    var node_11 = new Node(gameboard.context, node_11_loc);
    var node_12 = new Node(gameboard.context, node_12_loc);
    var node_13 = new Node(gameboard.context, node_13_loc);
    var node_14 = new Node(gameboard.context, node_14_loc);
    var node_15 = new Node(gameboard.context, node_15_loc);
    var node_16 = new Node(gameboard.context, node_16_loc);
    var node_17 = new Node(gameboard.context, node_17_loc);
    var node_18 = new Node(gameboard.context, node_18_loc);
    var node_19 = new Node(gameboard.context, node_19_loc);
    var node_20 = new Node(gameboard.context, node_20_loc);
    var node_21 = new Node(gameboard.context, node_21_loc);
    var node_22 = new Node(gameboard.context, node_22_loc);
    var node_23 = new Node(gameboard.context, node_23_loc);
    var node_24 = new Node(gameboard.context, node_24_loc);
    var node_25 = new Node(gameboard.context, node_25_loc);
    var node_26 = new Node(gameboard.context, node_26_loc);
    var node_27 = new Node(gameboard.context, node_27_loc);
    var node_28 = new Node(gameboard.context, node_28_loc);
    var node_29 = new Node(gameboard.context, node_29_loc);
    var node_30 = new Node(gameboard.context, node_30_loc);

    // third connect the nodes, running a connection from A->B will also create the connection from B->A
    node_0.connect(node_1);
    node_0.connect(node_29);
    node_1.connect(node_2);
    node_1.connect(node_6);
    node_2.connect(node_7);
    node_3.connect(node_8);
    node_3.connect(node_30);
    node_4.connect(node_5);
    node_5.connect(node_11);
    node_6.connect(node_12);
    node_7.connect(node_13);
    node_8.connect(node_9);
    node_9.connect(node_15);
    node_10.connect(node_11);
    node_10.connect(node_16);
    node_11.connect(node_12);
    node_13.connect(node_14);
    node_13.connect(node_19);
    node_14.connect(node_15);
    node_14.connect(node_20);
    node_16.connect(node_17);
    node_18.connect(node_19);
    node_18.connect(node_24);
    node_18.connect(node_26);
    node_20.connect(node_21);
    node_21.connect(node_22);
    node_22.connect(node_23);
    node_23.connect(node_24);
    node_23.connect(node_27);
    node_24.connect(node_25);
    node_26.connect(node_30);
    node_27.connect(node_28);
    node_28.connect(node_29);
    node_29.connect(node_30);

    // fourth add the nodes to the network
    networks.nodes = [node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9, node_10, node_11, node_12, node_13, node_14, node_15, node_16, node_17, node_18, node_19, node_20, node_21, node_22, node_23, node_24, node_25, node_26, node_27, node_28, node_29, node_30];

    //  fifth set the game parameters
    networks.observationNodes = [14, 24, 11];
    networks.optimalHops = 7;
    networks.maxRounds = 3;
}


// [autogenerated] Kilshin network - TreeShuffle
function generatePuzzleKilshinTreeShuffle() {
    // first record the location of each node, as an x% y% of the canvas
    var node_0_loc = [0.4043802965146589, 0.6706062912995617];
    var node_1_loc = [0.5900142433322495, 0.8528007801940815];
    var node_2_loc = [0.893341373592157, 0.678941003720637];
    var node_3_loc = [0.747075047227736, 0.2222920185165383];
    var node_4_loc = [0.6703122100532547, 0.7780995042036272];
    var node_5_loc = [0.4209805983941052, 0.5426000318348327];
    var node_6_loc = [0.4835902014086897, 0.8668183998394973];
    var node_7_loc = [0.3538222722213725, 0.42166762155021276];
    var node_8_loc = [0.10073583128869262, 0.43614762775450433];
    var node_9_loc = [0.6051488849058321, 0.8479688753493203];
    var node_10_loc = [0.8389412678061877, 0.3618798506592783];
    var node_11_loc = [0.8910888204952154, 0.2501399521876151];
    var node_12_loc = [0.7586016144288252, 0.2258075896672357];
    var node_13_loc = [0.42407892228892763, 0.15877864944582207];
    var node_14_loc = [0.7864311449584139, 0.763038456781218];
    var node_15_loc = [0.21183143883417302, 0.5216851812456661];
    var node_16_loc = [0.3065131975330451, 0.49342056001506895];
    var node_17_loc = [0.542564804759399, 0.18500964095900577];
    var node_18_loc = [0.791500450480906, 0.32295705522744966];
    var node_19_loc = [0.45769865725949865, 0.145806877372599];
    var node_20_loc = [0.10219616512659027, 0.25612761727758904];
    var node_21_loc = [0.3733401472946726, 0.842490736811659];
    var node_22_loc = [0.811782630807638, 0.4844008133169172];
    var node_23_loc = [0.463807854866065, 0.6335944350831045];
    var node_24_loc = [0.7870039219678833, 0.3698380045989592];
    var node_25_loc = [0.7349236222069249, 0.41918980247043514];
    var node_26_loc = [0.5752431059101659, 0.6899735862321815];
    var node_27_loc = [0.5010857635337009, 0.6526206169653596];
    var node_28_loc = [0.6578507858870408, 0.10457015194233454];
    var node_29_loc = [0.13125242660465153, 0.21923064865243963];
    var node_30_loc = [0.27090810747938604, 0.2625716856756255];

    // second create the node objects
    var node_0 = new Node(gameboard.context, node_0_loc);
    var node_1 = new Node(gameboard.context, node_1_loc);
    var node_2 = new Node(gameboard.context, node_2_loc);
    var node_3 = new Node(gameboard.context, node_3_loc);
    var node_4 = new Node(gameboard.context, node_4_loc);
    var node_5 = new Node(gameboard.context, node_5_loc);
    var node_6 = new Node(gameboard.context, node_6_loc);
    var node_7 = new Node(gameboard.context, node_7_loc);
    var node_8 = new Node(gameboard.context, node_8_loc);
    var node_9 = new Node(gameboard.context, node_9_loc);
    var node_10 = new Node(gameboard.context, node_10_loc);
    var node_11 = new Node(gameboard.context, node_11_loc);
    var node_12 = new Node(gameboard.context, node_12_loc);
    var node_13 = new Node(gameboard.context, node_13_loc);
    var node_14 = new Node(gameboard.context, node_14_loc);
    var node_15 = new Node(gameboard.context, node_15_loc);
    var node_16 = new Node(gameboard.context, node_16_loc);
    var node_17 = new Node(gameboard.context, node_17_loc);
    var node_18 = new Node(gameboard.context, node_18_loc);
    var node_19 = new Node(gameboard.context, node_19_loc);
    var node_20 = new Node(gameboard.context, node_20_loc);
    var node_21 = new Node(gameboard.context, node_21_loc);
    var node_22 = new Node(gameboard.context, node_22_loc);
    var node_23 = new Node(gameboard.context, node_23_loc);
    var node_24 = new Node(gameboard.context, node_24_loc);
    var node_25 = new Node(gameboard.context, node_25_loc);
    var node_26 = new Node(gameboard.context, node_26_loc);
    var node_27 = new Node(gameboard.context, node_27_loc);
    var node_28 = new Node(gameboard.context, node_28_loc);
    var node_29 = new Node(gameboard.context, node_29_loc);
    var node_30 = new Node(gameboard.context, node_30_loc);

    // third connect the nodes, running a connection from A->B will also create the connection from B->A
    node_0.connect(node_1);
    node_1.connect(node_2);
    node_1.connect(node_6);
    node_2.connect(node_7);
    node_3.connect(node_8);
    node_4.connect(node_5);
    node_5.connect(node_11);
    node_6.connect(node_12);
    node_7.connect(node_13);
    node_8.connect(node_9);
    node_9.connect(node_15);
    node_10.connect(node_11);
    node_10.connect(node_16);
    node_11.connect(node_12);
    node_13.connect(node_14);
    node_13.connect(node_19);
    node_14.connect(node_15);
    node_14.connect(node_20);
    node_16.connect(node_17);
    node_18.connect(node_19);
    node_18.connect(node_24);
    node_20.connect(node_21);
    node_22.connect(node_23);
    node_23.connect(node_24);
    node_23.connect(node_27);
    node_24.connect(node_25);
    node_26.connect(node_30);
    node_27.connect(node_28);
    node_28.connect(node_29);
    node_29.connect(node_30);

    // fourth add the nodes to the network
    networks.nodes = [node_0, node_1, node_2, node_3, node_4, node_5, node_6, node_7, node_8, node_9, node_10, node_11, node_12, node_13, node_14, node_15, node_16, node_17, node_18, node_19, node_20, node_21, node_22, node_23, node_24, node_25, node_26, node_27, node_28, node_29, node_30];

    //  fifth set the game parameters
    networks.observationNodes = [7, 27, 28];
    networks.optimalHops = 9;
    networks.maxRounds = 3;
}


